seed: 12
device: null

model: 
  name: IDRWKV
  scale: 2
  in_channels: 3
  num_channels: 64
  num_blocks: 3
  hidden_rate: 3
  embed_dim: 64
  num_heads: 8
  patch_size: 8
  with_cp: false
  checkpoint_dir: ./checkpoints/2X_IDRWKV_csplit_ft

optimizer:
  name: adam
  lr: 0.00005
  betas: [0.9, 0.99]
  
scheduler:
  lr_milestones: [50000, 75000, 87500, 93750]
  lr_gamma: 0.5

data:
  train_datasets: ['DIV2K', 'Flickr2K']
  train_dataset_dirs: [./training_data/DIV2K_train_HR, ./training_data/Flickr2K]
  scale: 2
  patch_size: [96, 96]
  batch_size: 8 # may need to change based on gpu memory
  num_workers: 4 # may need to change based on gpu memory
  persist_workers: true
  pin_memory: true
  prefetch_factor: 4

finetuner:
  num_iterations: 100000
  log_freq: 100
  logging: true
  checkpoint_freq: 2000
  resume: true

wandb:
  entity: farns301
  project: IDRWKV-2x-csplitft
  run_name: idrwkv_2x_csplitft
  resume: allow
  id: 'run_30_2x'