seed: 12
device: null

model: 
  name: IDRWKV
  scale: 3
  in_channels: 3
  num_channels: 64
  num_blocks: 3
  hidden_rate: 3
  embed_dim: 64
  num_heads: 8
  patch_size: 8
  with_cp: false
  checkpoint_dir: ./checkpoints/3X_IDRWKV_fftloss_ws

optimizer:
  name: adam
  lr: 0.0005
  betas: [0.9, 0.99]

scheduler:
  lr_milestones: [125000, 200000, 225000, 237500]
  lr_gamma: 0.5

data:
  train_datasets: ['DIV2K', 'Flickr2K']
  train_dataset_dirs: [./training_data/DIV2K_train_HR, ./training_data/Flickr2K]
  scale: 3
  patch_size: [64, 64]
  batch_size: 16 # may need to change based on gpu memory
  num_workers: 4 # may need to change based on gpu memory
  persist_workers: true
  pin_memory: true
  prefetch_factor: 4

trainer:
  num_iterations: 250000
  log_freq: 100
  logging: true
  checkpoint_freq: 5000
  resume: true

wandb:
  entity: farns301
  project: RWKVSR-3-ws3x
  run_name: rwkv6sr9_3x_fftloss_ws
  resume: allow
  id: 'run_25_4x'