seed: 12
device: null

model: 
  name: RWKVSR
  scale: 2
  in_channels: 3
  num_channels: 64
  blocks_per_layer: 1
  residual_groups: 3
  hidden_rate: 3
  embed_dim: 64
  num_heads: 8
  patch_size: 8
  with_cp: false
  checkpoint_dir: ./checkpoints/2X_RWKV6_9SR_ft3

optimizer:
  name: adam
  lr: 0.00005
  betas: [0.9, 0.99]

  # name: adamw
  # lr: 0.0002
  # betas: [0.9, 0.99]
  # weight_decay: 0.001
  
scheduler:
  lr_milestones: [80000, 140000, 180000]
  lr_gamma: 0.5

data:
  train_datasets: ['DIV2K', 'Flickr2K']
  train_dataset_dirs: [./training_data/DIV2K_train_HR, ./training_data/Flickr2K]
  scale: 2
  patch_size: [128, 128]
  batch_size: 8 # may need to change based on gpu memory
  num_workers: 4 # may need to change based on gpu memory
  persist_workers: true
  pin_memory: true
  prefetch_factor: 4

finetuner:
  num_iterations: 200000
  log_freq: 100
  logging: true
  checkpoint_freq: 2000
  resume: true

wandb:
  entity: farns301
  project: RWKVSR-3-ft 
  run_name: rwkv6sr9_2x_lite_higherlr_ft3
  resume: allow
  id: 'run_10_2x'